name: reviewdog
on: [pull_request]
permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: reviewdog/action-actionlint@v1

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: npm ci
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          level: warning
          eslint_flags: "src/**/*.ts __tests__/**/*.ts"
