name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: |
          npm ci
      - run: |
          npm run all

  # make sure the action works on a clean machine without building
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          shell: bash
          run: |
            set -euxo pipefail
            echo "RUNNING"
            pwd
